apiVersion: apps/v1
kind: Deployment
metadata:
  name: toshi-bitcoin-parser-deployment-{{ .Values.bitcoin.client }}
  labels:
    app: toshi-bitcoin-parser-{{ .Values.bitcoin.client }}
    tier: bitcoin-{{ .Values.bitcoin.client }}
spec:
  replicas:
  selector:
    matchLabels:
      app: toshi-bitcoin-parser-{{ .Values.bitcoin.client }}
      tier: bitcoin-{{ .Values.bitcoin.client }}
  template:
    metadata:
      labels:
        app: toshi-bitcoin-parser-{{ .Values.bitcoin.client }}
        tier: bitcoin-{{ .Values.bitcoin.client }}
    spec:
      {{- if and .Values.bitcoin.nodeSelector.key .Values.bitcoin.nodeSelector.value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: {{ .Values.bitcoin.nodeSelector.key }}
                    operator: In
                    values:
                      - {{ .Values.bitcoin.nodeSelector.value }}
      {{- end }}
      volumes:
        - name: toshi-bitcoin-parser-pv-storage
          persistentVolumeClaim:
            claimName: toshi-bitcoin-parser-pv-claim
      containers:
        - name: bitcoin-core
          image: "{{ .Values.bitcoin.image.name }}:{{ .Values.bitcoin.image.tag }}"
          imagePullPolicy: {{ .Values.bitcoin.image.pullPolicy }}
          volumeMounts:
            - name: toshi-bitcoin-parser-pv-storage
              mountPath: {{ .Values.bitcoin.image.volume.mountPath }}
          env:
            - name: MOUNT_PATH
              value: {{ .Values.bitcoin.image.volume.mountPath }}
            - name: START_BLOCK_HEIGHT
              value: {{ .Values.bitcoin.parser.startBlockHeight | quote }}
            - name: END_BLOCK_HEIGHT
              value: {{ .Values.bitcoin.parser.endBlockHeight | quote }}
            - name: BATCH_SIZE
              value: {{ .Values.bitcoin.parser.batchSize | quote }}
            - name: BITCOIN_DAEMON_HOST
              value: {{ .Values.bitcoin.parser.bitcoinDaemonHost | quote }}
            - name: BITCOIN_DAEMON_USERNAME
              value: {{ .Values.bitcoin.parser.bitcoinDaemonUsername | quote }}
            - name: BITCOIN_DAEMON_PASSWORD
              value: {{ .Values.bitcoin.parser.bitcoinDaemonPassword | quote }}
            - name: BITCOIN_DAEMON_PORT
              value: {{ .Values.bitcoin.parser.bitcoinDaemonPort | quote }}
