bitcoin:
  image:
    name: "toshiqcri/btc-etl-parser"
    tag: "latest"
    pullPolicy: Always
    volume:
      mountPath: "/blockchain-parser/data/"
  storage:
    className: "managed-nfs-storage"
    size: "10Gi"
  nodeSelector:
    key: "kubernetes.io/hostname"
    value: "cybubtoshicl012"
  service:
    port: 8332
    targetPort: 8332
  client: 1
  parser:
    startBlockHeight: "200000"
    endBlockHeight: "300000"
    batchSize: "10000"
    bitcoinDaemonHost: "bitcoin-daemon-service-readonly-1"
    bitcoinDaemonUsername: "user"
    bitcoinDaemonPassword: "password"
    bitcoinDaemonPort: "30234"
