bitcoin:
  image:
    name: "sajithagimash/bitcoin-daemon-read-only"
    tag: "1.0.0"
    pullPolicy: Always
    volume:
      mountPath: "/mnt/data/bitcoin"
  nodeSelector:
    key: "kubernetes.io/hostname"
    value: "cybubtoshicl012"
  service:
    port: 8332
    targetPort: 8332
    nodePort: 30234
  client: 1
