apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum-client-deployment-{{ .Values.ethereum.client }}
  labels:
    app: ethereum-client-{{ .Values.ethereum.client }}
    tier: ethereum-{{ .Values.ethereum.client }}
spec:
  replicas:
  selector:
    matchLabels:
      app: ethereum-client-{{ .Values.ethereum.client }}
      tier: ethereum-{{ .Values.ethereum.client }}
  template:
    metadata:
      labels:
        app: ethereum-client-{{ .Values.ethereum.client }}
        tier: ethereum-{{ .Values.ethereum.client }}
    spec:
      {{- if and .Values.ethereum.nodeSelector.key .Values.ethereum.nodeSelector.value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: {{ .Values.ethereum.nodeSelector.key }}
                    operator: In
                    values:
                      - {{ .Values.ethereum.nodeSelector.value }}
      {{- end }}
      volumes:
        - name: geth-ipc
          persistentVolumeClaim:
            claimName: ethereum-client-pv-claim-{{ .Values.ethereum.client }}
      containers:
        - name: ethereum-core
          image: "{{ .Values.ethereum.image.name }}:{{ .Values.ethereum.image.tag }}"
          command: ['/bin/sh', '-c', 'geth --gcmode archive --syncmode full  --cache=4096 --http --http.port=8545 --http.addr=0.0.0.0 --http.api="admin,debug,web3,eth,personal" --http.vhosts="*" --txlookuplimit=0 --vmdebug --log.debug --allow-insecure-unlock']
          ports:
          - name: rpc
            containerPort: 8545
          - name: ws
            containerPort: 8546
          - name: p2p
            containerPort: 30303
          imagePullPolicy: {{ .Values.ethereum.image.pullPolicy }}
          volumeMounts:
            - name: geth-ipc
              mountPath: /root/

---
apiVersion: v1
kind: Service
metadata:
  name: ethereum-client-service-{{ .Values.ethereum.client }}
  labels:
    tier: ethereum-{{ .Values.ethereum.client }}
spec:
  selector:
    app: ethereum-client-{{ .Values.ethereum.client }}
    tier: ethereum-{{ .Values.ethereum.client }}
  type: NodePort
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
    nodePort: 31352
  - name: ws
    port: 8546
  - name: p2p
    port: 30303
  externalIPs: 
    - 10.4.8.131
