kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ethereum-client-pv-claim-{{ .Values.ethereum.client }}
spec:
  storageClassName: {{ .Values.ethereum.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ethereum.storage.size }}
