ethereum:
  image:
    name: 'ethereum/client-go'
    tag: 'latest'
    pullPolicy: IfNotPresent
  storage:
    className: 'managed-nfs-storage'
    size: '1200Gi'
  nodeSelector:
    key: 'kubernetes.io/hostname'
    value: 'cybubcibrdev001'
  client: 1