kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cibr-airflow-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Gi"
