apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-daemon-sync-deployment
  labels:
    app: bitcoin-daemon-sync
    tier: bitcoin-sync
spec:
  replicas:
  selector:
    matchLabels:
      app: bitcoin-daemon-sync
      tier: bitcoin-sync
  template:
    metadata:
      labels:
        app: bitcoin-daemon-sync
        tier: bitcoin-sync
    spec:
      {{- if and .Values.bitcoin.nodeSelector.key .Values.bitcoin.nodeSelector.value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: {{ .Values.bitcoin.nodeSelector.key }}
                    operator: In
                    values:
                      - {{ .Values.bitcoin.nodeSelector.value }}
      {{- end }}
      volumes:
        - name: bitcoin-daemon-pv-storage
          persistentVolumeClaim:
            claimName: bitcoin-daemon-sync-pv-claim
      containers:
        - name: bitcoin-core
          image: "{{ .Values.bitcoin.image.name }}:{{ .Values.bitcoin.image.tag }}"
          ports:
          - containerPort: {{ .Values.bitcoin.service.targetPort }}
          resources:
            requests:
              memory: "10Gi"
              cpu: 2
            limits:
              memory: "25Gi"
              cpu: 8  
          imagePullPolicy: {{ .Values.bitcoin.image.pullPolicy }}
          volumeMounts:
            - name: bitcoin-daemon-pv-storage
              mountPath: {{ .Values.bitcoin.image.volume.mountPath }}
          env:
            - name: MOUNT_PATH
              value: {{ .Values.bitcoin.image.volume.mountPath }}

---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-daemon-sync-service
  labels:
    tier: bitcoin-sync
spec:
  selector:
    app: bitcoin-daemon-sync
    tier: bitcoin-sync
  ports:
    - targetPort: {{ .Values.bitcoin.service.targetPort }}
      port: {{ .Values.bitcoin.service.port }}
      protocol: TCP